name: Contribution License Agreement (CLA)
description: Sign the CLA
title: "[CLA]: <@yourusername> Signing"
labels: ["cla"]
projects: ["termsurf/text.js"]
assignees:
  - lancejpollard
body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting or working on contributing some code changes to our projects!

        In order for us to accept your code change, you must sign our [Contribution License Agreement (CLA)](https://github.com/termsurf/.github/blob/abc3b8c8016e13cc709520969370076ac5ee1d17/CONTRIBUTION_LICENSE_AGREEMENT.md) before your PR will be merged. This a one-time requirement for TermSurf projects on GitHub. You can read more about [Contribution License Agreements](https://en.wikipedia.org/wiki/Contributor_License_Agreement) on Wikipedia.

        Basically, this [CLA](https://github.com/termsurf/.github/blob/abc3b8c8016e13cc709520969370076ac5ee1d17/CONTRIBUTION_LICENSE_AGREEMENT.md) allows TermSurf to use, modify, and distribute contributions you make to their open-source projects, with a perpetual, worldwide license for both copyright and patents. You affirm that your submissions are original or properly attributed, and if made on behalf of an employer, you have obtained the necessary permissions.

        Once you have signed a CLA, the current and all future pull-requests will be labeled as cla-signed.

        Signing the CLA might sound scary but it's actually very simple and can be done in less than a minute.
  - type: input
    id: name
    attributes:
      label: Name ("You")
      description: Your full name
      placeholder: eg. Jane Smith
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      description: Today's Date
      placeholder: eg. Dec 12, 2023
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: GitHub Username
      placeholder: eg. @foobar
    validations:
      required: true
  - type: input
    id: company
    attributes:
      label: Company Name
      description: Only need to put a company name if you mark "Employee" down below, if you are not contributing this as an individual.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: I Agree to the CLA (select one)
      description: |
        By submitting this issue, you agree to the [CLA](https://github.com/termsurf/.github/blob/abc3b8c8016e13cc709520969370076ac5ee1d17/CONTRIBUTION_LICENSE_AGREEMENT.md). Note: **Individual** means you are _not_ contributing on behalf of an employer, while **Employee** means you _are_ contributing on behalf of an employer (this option is more rare).
      options:
        - label: |
            **Individual**: I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
        - label: |
            **Employee**: I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term "You" includes me and my employer.
